
from PIL import Image
import numpy as np
from typing import List, Tuple, Union, Iterator


class LoadPilAndNumpy:
    '''
    Load images from PIL and Numpy arrays for batch processing.
    This class manages loading and pre-processing of image data from both PIL and Numpy formats. It performs basic
    validation and format conversion to ensure that the images are in the required format for downstream processing.
    Attributes:
        paths (List[str]): List of image paths or autogenerated filenames.
        im0 (List[np.ndarray]): List of images stored as Numpy arrays.
        mode (str): Type of data being processed, set to 'image'.
        bs (int): Batch size, equivalent to the length of `im0`.
    Methods:
        _single_check: Validate and format a single image to a Numpy array.
    Examples:
        >>> from PIL import Image
        >>> import numpy as np
        >>> pil_img = Image.new("RGB", (100, 100))
        >>> np_img = np.random.randint(0, 255, (100, 100, 3), dtype=np.uint8)
        >>> loader = LoadPilAndNumpy([pil_img, np_img])
        >>> paths, images, _ = next(iter(loader))
        >>> print(f"Loaded {len(images)} images")
        Loaded 2 images
    '''

    def __init__(self, im0: List[Union[Image.Image, np.ndarray]]):
        '''Initializes a loader for PIL and Numpy images, converting inputs to a standardized format.'''
        self.im0 = [self._single_check(im) for im in im0]
        self.paths = [f'image_{i}' for i in range(len(im0))]
        self.mode = 'image'
        self.bs = len(im0)
        self._index = 0

    @staticmethod
    def _single_check(im: Union[Image.Image, np.ndarray]) -> np.ndarray:
        '''Validate and format an image to numpy array, ensuring RGB order and contiguous memory.'''
        if isinstance(im, Image.Image):
            im = np.array(im)
        if im.ndim == 2:  # Grayscale to RGB
            im = np.stack((im,) * 3, axis=-1)
        elif im.shape[2] == 4:  # RGBA to RGB
            im = im[:, :, :3]
        return np.ascontiguousarray(im)

    def __len__(self) -> int:
        '''Returns the length of the 'im0' attribute, representing the number of loaded images.'''
        return self.bs

    def __next__(self) -> Tuple[List[str], List[np.ndarray], dict]:
        '''Returns the next batch of images, paths, and metadata for processing.'''
        if self._index >= self.bs:
            self._index = 0
            raise StopIteration
        batch_paths = self.paths[self._index:self._index + self.bs]
        batch_images = self.im0[self._index:self._index + self.bs]
        self._index += self.bs
        return batch_paths, batch_images, {}

    def __iter__(self) -> Iterator[Tuple[List[str], List[np.ndarray], dict]]:
        '''Iterates through PIL/numpy images, yielding paths, raw images, and metadata for processing.'''
        self._index = 0
        return self
