class TraceId:
    '''
    A trace ID tracks the path of a request through your application.
    A trace collects all the segments generated by a single request.
    A trace ID is required for a segment.
    '''

    def __init__(self):
        '''
        Generate a random trace id.
        '''
        import time
        import secrets

        version = "1"
        timestamp_hex = format(int(time.time()), "08x")
        random_hex = secrets.token_hex(12)  # 96-bit random identifier
        self._id = f"{version}-{timestamp_hex}-{random_hex}"

    def to_id(self):
        '''
        Convert TraceId object to a string.
        '''
        return self._id
