
import random
import string


class TraceId:
    '''
    A trace ID tracks the path of a request through your application.
    A trace collects all the segments generated by a single request.
    A trace ID is required for a segment.
    '''

    def __init__(self):
        '''
        Generate a random trace id.
        '''
        self.id = ''.join(random.choices(string.hexdigits.lower(), k=32))

    def to_id(self):
        '''
        Convert TraceId object to a string.
        '''
        return self.id
