
from PIL import Image
import numpy as np
from typing import List, Union


class LoadPilAndNumpy:
    '''
    Load images from PIL and Numpy arrays for batch processing.
    This class manages loading and pre-processing of image data from both PIL and Numpy formats. It performs basic
    validation and format conversion to ensure that the images are in the required format for downstream processing.
    Attributes:
        paths (List[str]): List of image paths or autogenerated filenames.
        im0 (List[np.ndarray]): List of images stored as Numpy arrays.
        mode (str): Type of data being processed, set to 'image'.
        bs (int): Batch size, equivalent to the length of `im0`.
    Methods:
        _single_check: Validate and format a single image to a Numpy array.
    Examples:
        >>> from PIL import Image
        >>> import numpy as np
        >>> pil_img = Image.new("RGB", (100, 100))
        >>> np_img = np.random.randint(0, 255, (100, 100, 3), dtype=np.uint8)
        >>> loader = LoadPilAndNumpy([pil_img, np_img])
        >>> paths, images, _ = next(iter(loader))
        >>> print(f"Loaded {len(images)} images")
        Loaded 2 images
    '''

    def __init__(self, im0: List[Union[Image.Image, np.ndarray]]):
        self.paths = [f'image_{i}' for i in range(len(im0))]
        self.im0 = [self._single_check(im) for im in im0]
        self.mode = 'image'
        self.bs = len(self.im0)
        self._index = 0

    @staticmethod
    def _single_check(im: Union[Image.Image, np.ndarray]) -> np.ndarray:
        if isinstance(im, Image.Image):
            return np.array(im)
        elif isinstance(im, np.ndarray):
            if im.ndim == 2:
                return np.stack((im,) * 3, axis=-1)  # Convert grayscale to RGB
            elif im.ndim == 3 and im.shape[2] == 3:
                return im
            else:
                raise ValueError(
                    "Numpy array must be 2D (grayscale) or 3D with 3 channels (RGB).")
        else:
            raise TypeError("Image must be a PIL Image or a Numpy array.")

    def __len__(self):
        return self.bs

    def __next__(self):
        if self._index >= self.bs:
            self._index = 0
            raise StopIteration
        else:
            start = self._index
            end = start + 1
            self._index = end
            return self.paths[start:end], self.im0[start:end], self.mode

    def __iter__(self):
        self._index = 0
        return self
