
import argparse


class DependenciesConfiguration:
    '''Dependency configuration class, for RuntimeContext.job_script_provider.'''

    def __init__(self, args: argparse.Namespace) -> None:
        '''Initialize.'''
        self.args = args

    def build_job_script(self, builder: 'Builder', command: list[str]) -> str:
        dependencies = self.args.dependencies if hasattr(
            self.args, 'dependencies') else []
        script_lines = [
            '#!/bin/bash',
            '# Job script generated by DependenciesConfiguration',
        ]
        script_lines.extend([f'pip install {dep}' for dep in dependencies])
        script_lines.append(' '.join(command))
        return '\n'.join(script_lines)
