
from dataclasses import dataclass
import json
from pathlib import Path


@dataclass
class MultiSearchResult:
    '''Enhanced search result with comprehensive snippet metadata.'''

    def __str__(self) -> str:
        '''Return enhanced formatted string representation.'''
        return f"MultiSearchResult({self.__dict__})"

    def to_json(self) -> str:
        return json.dumps(self.__dict__)

    @classmethod
    def to_jsonlines(cls, results: list['MultiSearchResult']) -> str:
        '''Convert multiple MultiSearchResult objects to JSON Lines format.
        Args:
            results: List of MultiSearchResult objects
            include_summary: Whether to include summary fields
        Returns:
            JSON Lines string (one JSON object per line)
        '''
        return '\n'.join(result.to_json() for result in results)

    @classmethod
    def to_string(cls, results: list['MultiSearchResult']) -> str:
        '''Convert multiple MultiSearchResult objects to a string.'''
        return '\n'.join(str(result) for result in results)

    @staticmethod
    def calculate_relative_path(file_path: str, source_path: str) -> str:
        '''Calculate relative path from source root.'''
        return str(Path(file_path).relative_to(source_path))

    @staticmethod
    def detect_language_from_extension(extension: str) -> str:
        '''Detect programming language from file extension.'''
        extension_to_language = {
            '.py': 'Python',
            '.js': 'JavaScript',
            '.java': 'Java',
            '.c': 'C',
            '.cpp': 'C++',
            '.h': 'C/C++ Header',
            '.hpp': 'C++ Header',
            '.cs': 'C#',
            '.go': 'Go',
            '.rb': 'Ruby',
            '.php': 'PHP',
            '.swift': 'Swift',
            '.kt': 'Kotlin',
            '.rs': 'Rust',
            '.scala': 'Scala',
            '.ts': 'TypeScript',
            '.m': 'Objective-C',
            '.mm': 'Objective-C++',
            '.r': 'R',
            '.pl': 'Perl',
            '.lua': 'Lua',
            '.sh': 'Shell',
            '.bash': 'Bash',
            '.zsh': 'Zsh',
            '.ps1': 'PowerShell',
            '.bat': 'Batch',
            '.cmd': 'Batch',
            '.vb': 'Visual Basic',
            '.vbs': 'VBScript',
            '.f': 'Fortran',
            '.f90': 'Fortran 90',
            '.f95': 'Fortran 95',
            '.f03': 'Fortran 2003',
            '.f08': 'Fortran 2008',
            '.ada': 'Ada',
            '.adb': 'Ada',
            '.ads': 'Ada',
            '.pas': 'Pascal',
            '.dpr': 'Delphi',
            '.lisp': 'Lisp',
            '.cl': 'Common Lisp',
            '.scm': 'Scheme',
            '.rkt': 'Racket',
            '.ml': 'OCaml',
            '.mli': 'OCaml Interface',
            '.hs': 'Haskell',
            '.erl': 'Erlang',
            '.hrl': 'Erlang Header',
            '.ex': 'Elixir',
            '.exs': 'Elixir Script',
            '.clj': 'Clojure',
            '.cljs': 'ClojureScript',
            '.edn': 'edn',
            '.groovy': 'Groovy',
            '.gvy': 'Groovy',
            '.gy': 'Groovy',
            '.gsh': 'Groovy Shell',
            '.dart': 'Dart',
            '.jl': 'Julia',
            '.nim': 'Nim',
            '.cr': 'Crystal',
            '.v': 'Verilog',
            '.sv': 'SystemVerilog',
            '.vhd': 'VHDL',
            '.vhdl': 'VHDL',
            '.asm': 'Assembly',
            '.s': 'Assembly',
            '.coffee': 'CoffeeScript',
            '.jsx': 'JSX',
            '.tsx': 'TSX',
            '.html': 'HTML',
            '.htm': 'HTML',
            '.css': 'CSS',
            '.scss': 'SCSS',
            '.sass': 'Sass',
            '.less': 'Less',
            '.xml': 'XML',
            '.json': 'JSON',
            '.yaml': 'YAML',
            '.yml': 'YAML',
            '.toml': 'TOML',
            '.ini': 'INI',
            '.cfg': 'Configuration',
            '.conf': 'Configuration',
            '.properties': 'Properties',
            '.md': 'Markdown',
            '.markdown': 'Markdown',
            '.rst': 'reStructuredText',
            '.tex': 'TeX',
            '.txt': 'Text',
            '.csv': 'CSV',
            '.tsv': 'TSV',
            '.sql': 'SQL',
            '.graphql': 'GraphQL',
            '.gql': 'GraphQL',
            '.proto': 'Protocol Buffers',
            '.thrift': 'Apache Thrift',
            '.avdl': 'Avro IDL',
            '.asdl': 'ASN.1',
            '.dtd': 'DTD',
            '.xsd': 'XSD',
            '.wsdl': 'WSDL',
            '.xhtml': 'XHTML',
            '.svg': 'SVG',
            '.rdf': 'RDF',
            '.owl': 'OWL',
            '.ttl': 'Turtle',
            '.n3': 'N3',
            '.nt': 'NTriples',
            '.jsonld': 'JSON-LD',
            '.csv': 'CSV',
            '.tsv': 'TSV',
            '.parquet': 'Parquet',
            '.avro': 'Avro',
            '.orc': 'ORC',
            '.feather': 'Feather',
            '.hdf5': 'HDF5',
            '.h5': 'HDF5',
            '.npz': 'NumPy',
            '.npy': 'NumPy',
            '.pkl': 'Pickle',
            '.pickle': 'Pickle',
            '.joblib': 'Joblib',
            '.dill': 'Dill',
            '.sqlite': 'SQLite',
            '.db': 'Database',
            '.mdb': 'Microsoft Access',
            '.accdb': 'Microsoft Access',
            '.sqlite3': 'SQLite',
            '.db3': 'SQLite',
            '.db-journal': 'SQLite Journal',
            '.log': 'Log',
            '.txt': 'Text',
            '.csv': 'CSV',
            '.tsv': 'TSV',
            '.json': 'JSON',
            '.yaml': 'YAML',
            '.yml': 'YAML',
            '.toml': 'TOML',
            '.ini': 'INI',
            '.cfg': 'Configuration',
            '.conf': 'Configuration',
            '.properties': 'Properties',
            '.md': 'Markdown',
            '.markdown': 'Markdown',
            '.rst': 'reStructuredText',
            '.tex': 'TeX',
            '.txt': 'Text',
            '.csv': 'CSV',
            '.tsv': 'TSV',
            '.sql': 'SQL',
            '.graphql': 'GraphQL',
            '.gql': 'GraphQL',
            '.proto': 'Protocol Buffers',
            '.thrift': 'Apache Thrift',
            '.avdl': 'Avro IDL',
            '.asdl': 'ASN.1',
            '.dtd': 'DTD',
            '.xsd': 'XSD',
            '.wsdl': 'WSDL',
            '.xhtml': 'XHTML',
            '.svg': 'SVG',
            '.rdf': 'RDF',
            '.owl': 'OWL',
            '.ttl': 'Turtle',
            '.n3': 'N3',
            '.nt': 'NTriples',
            '.jsonld': 'JSON-LD',
            '.csv': 'CSV',
            '.tsv': 'TSV',
            '.parquet': 'Parquet',
            '.avro': 'Avro',
            '.orc': 'ORC',
            '.feather': 'Feather',
            '.hdf5': 'HDF5',
            '.h5': 'HDF5',
            '.npz': 'NumPy',
            '.npy': 'NumPy',
            '.pkl': 'Pickle',
            '.pickle': 'Pickle',
            '.joblib': 'Joblib',
            '.dill': 'Dill',
            '.sqlite': 'SQLite',
            '.db': 'Database',
            '.mdb': 'Microsoft Access',
            '.accdb': 'Microsoft Access',
            '.sqlite3': 'SQLite',
            '.db3': 'SQLite',
            '.db-journal': 'SQLite Journal',
            '.log': 'Log',
        }
        return extension_to_language.get(extension.lower(), 'Unknown')
