
import uuid


class NoOpTraceId:
    '''
    A trace ID tracks the path of a request through your application.
    A trace collects all the segments generated by a single request.
    A trace ID is required for a segment.
    '''

    def __init__(self):
        '''
        Generate a no-op trace id.
        '''
        self.trace_id = str(uuid.uuid4())

    def to_id(self):
        '''
        Convert TraceId object to a string.
        '''
        return self.trace_id
