
from __future__ import annotations

from datetime import datetime
from typing import List, Optional

try:
    # Python 3.9+
    from zoneinfo import ZoneInfo
except ImportError:
    # Fallback for older Python versions
    from pytz import timezone as ZoneInfo  # type: ignore

from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich import box
from rich.style import Style
from rich.align import Align
from rich.table import Table
from rich import print as rprint
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import inspect
from rich import pretty
from rich import inspect
from rich import traceback
from rich import
