
import uuid


class TraceId:
    '''
    A trace ID tracks the path of a request through your application.
    A trace collects all the segments generated by a single request.
    A trace ID is required for a segment.
    '''

    def __init__(self):
        '''
        Generate a random trace id.
        '''
        self.id = str(uuid.uuid4()).replace('-', '')

    def to_id(self):
        '''
        Convert TraceId object to a string.
        '''
        return self.id


# Example usage:
if __name__ == "__main__":
    trace_id = TraceId()
    print(trace_id.to_id())
