class NoOpTraceId:
    '''
    A trace ID tracks the path of a request through your application.
    A trace collects all the segments generated by a single request.
    A trace ID is required for a segment.
    '''

    def __init__(self):
        '''
        Generate a no-op trace id.
        '''
        # Use a fixed placeholder ID for no-op traces
        self._id = "0000000000000000"

    def to_id(self):
        '''
        Convert TraceId object to a string.
        '''
        return self._id
