
from typing import List
import numpy as np
from PIL import Image


class LoadPilAndNumpy:
    '''
    Load images from PIL and Numpy arrays for batch processing.
    This class manages loading and pre-processing of image data from both PIL and Numpy formats. It performs basic
    validation and format conversion to ensure that the images are in the required format for downstream processing.
    Attributes:
        paths (List[str]): List of image paths or autogenerated filenames.
        im0 (List[np.ndarray]): List of images stored as Numpy arrays.
        mode (str): Type of data being processed, set to 'image'.
        bs (int): Batch size, equivalent to the length of `im0`.
    Methods:
        _single_check: Validate and format a single image to a Numpy array.
    Examples:
        >>> from PIL import Image
        >>> import numpy as np
        >>> pil_img = Image.new("RGB", (100, 100))
        >>> np_img = np.random.randint(0, 255, (100, 100, 3), dtype=np.uint8)
        >>> loader = LoadPilAndNumpy([pil_img, np_img])
        >>> paths, images, _ = next(iter(loader))
        >>> print(f"Loaded {len(images)} images")
        Loaded 2 images
    '''

    def __init__(self, im0):
        self.im0 = [self._single_check(im) for im in im0]
        self.paths = [f"image_{i}.jpg" for i in range(len(im0))]
        self.mode = 'image'
        self.bs = len(im0)
        self.index = 0

    @staticmethod
    def _single_check(im):
        if isinstance(im, Image.Image):
            im = np.array(im)
        elif not isinstance(im, np.ndarray):
            raise TypeError("Input must be a PIL Image or a Numpy array")
        if im.dtype != np.uint8:
            im = im.astype(np.uint8)
        if len(im.shape) != 3 or im.shape[2] not in [1, 3, 4]:
            raise ValueError(
                "Invalid image shape. Expected (H, W, C) where C is 1, 3 or 4")
        return im

    def __len__(self):
        return self.bs

    def __next__(self):
        if self.index < self.bs:
            im = self.im0[self.index]
            path = self.paths[self.index]
            self.index += 1
            return path, im, self.mode
        else:
            self.index = 0
            raise StopIteration

    def __iter__(self):
        return self
